repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - "--baseline"
          - ".secrets.baseline"
          - "--exclude-files"
          - "^context/"
          - "--exclude-files"
          - "^frontend/messages/(en|pl|de)\\.json$"
          - "--exclude-files"
          - "^backend/alembic/versions/"

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
