"""add_email_reminder_fields

Revision ID: 26af8e218f0f
Revises: d6fac3b08953
Create Date: 2026-06-15 22:07:37.800993

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "26af8e218f0f"
down_revision: Union[str, Sequence[str], None] = "d6fac3b08953"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_bill_templates_user_id"), "bill_templates", type_="foreignkey"
    )
    op.create_foreign_key(
        "bill_templates_user_id_fkey",
        "bill_templates",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "payment_instances",
        sa.Column(
            "reminder_sent_upcoming",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "payment_instances",
        sa.Column(
            "reminder_sent_overdue",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_reminders_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_reminders_enabled")
    op.drop_column("payment_instances", "reminder_sent_overdue")
    op.drop_column("payment_instances", "reminder_sent_upcoming")
    op.drop_constraint(
        "bill_templates_user_id_fkey", "bill_templates", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_bill_templates_user_id"),
        "bill_templates",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
