"""add_language_preference_to_users

Revision ID: 632d778e4aa5
Revises: e3eb40b9157b
Create Date: 2026-06-12 10:18:20.630903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "632d778e4aa5"
down_revision: Union[str, Sequence[str], None] = "e3eb40b9157b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bill_templates",
        sa.Column(
            "currency", sa.String(length=10), nullable=False, server_default="PLN"
        ),
    )
    op.alter_column("bill_templates", "currency", server_default=None)
    op.add_column(
        "users", sa.Column("language_preference", sa.String(length=5), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language_preference")
    op.drop_column("bill_templates", "currency")
    # ### end Alembic commands ###
