"""add_start_period_to_bill_templates

Revision ID: 68cc4b807b16
Revises: 632d778e4aa5
Create Date: 2026-06-15 07:30:11.277930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "68cc4b807b16"
down_revision: Union[str, Sequence[str], None] = "632d778e4aa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bill_templates", sa.Column("start_period", sa.String(length=7), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bill_templates", "start_period")
    # ### end Alembic commands ###
