"""initial schema

Revision ID: 6a0cd67ba730
Revises:
Create Date: 2026-07-23 18:16:29.302124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6a0cd67ba730"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("language_preference", sa.String(length=5), nullable=True),
        sa.Column(
            "email_reminders_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column(
            "notify_2_days_before", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "notify_1_day_before", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "notify_on_day", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "notify_1_day_after", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "reminder_send_minute", sa.Integer(), server_default="480", nullable=False
        ),
        sa.Column(
            "monthly_summary_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column(
            "monthly_summary_last_sent",
            sa.String(length=7),
            server_default="null",
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_reminder_send_minute", "users", ["reminder_send_minute"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "bill_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("due_day", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("is_paused", sa.Boolean(), nullable=False),
        sa.Column("start_period", sa.String(length=7), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_bill_templates_user_active",
        "bill_templates",
        ["user_id", "is_archived", "is_paused"],
        unique=False,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"),
        "password_reset_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "restore_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "payment_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "reminder_sent_upcoming",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "reminder_sent_overdue",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "reminder_sent_2_days_before",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "reminder_sent_on_day", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("email_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bill_id", "period", name="uq_payment_instance_bill_period"
        ),
    )
    op.create_index(
        "ix_payment_instance_due_date", "payment_instances", ["due_date"], unique=False
    )
    op.create_index(
        "ix_payment_instance_period_active",
        "payment_instances",
        ["period", "is_deleted"],
        unique=False,
    )
    op.create_index(
        "ix_payment_instance_user_id_via_join",
        "payment_instances",
        ["bill_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_payment_instance_user_id_via_join", table_name="payment_instances"
    )
    op.drop_index("ix_payment_instance_period_active", table_name="payment_instances")
    op.drop_index("ix_payment_instance_due_date", table_name="payment_instances")
    op.drop_table("payment_instances")
    op.drop_table("restore_snapshots")
    op.drop_index(
        op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_index("ix_bill_templates_user_active", table_name="bill_templates")
    op.drop_table("bill_templates")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("ix_user_reminder_send_minute", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
